import AppKit

class FlippedView: NSView {
    override var isFlipped: Bool { true }
}

// MARK: - Hoverable chip card for welcome suggestions

class HoverChipView: NSView {
    var onTapped: (() -> Void)?
    private let normalBg: CGColor
    private let hoverBg: CGColor
    private weak var contentStack: NSStackView?

    init(symbol: String, label: String, theme: PopoverTheme) {
        self.normalBg = theme.inputBg.cgColor
        self.hoverBg = theme.accentColor.withAlphaComponent(0.06).cgColor
        super.init(frame: .zero)

        wantsLayer = true
        layer?.backgroundColor = normalBg
        layer?.cornerRadius = 10
        layer?.borderWidth = 1.0
        layer?.borderColor = theme.separatorColor.withAlphaComponent(0.55).cgColor
        translatesAutoresizingMaskIntoConstraints = false

        let hStack = NSStackView()
        hStack.orientation = .horizontal
        hStack.alignment = .centerY
        hStack.spacing = 10
        hStack.edgeInsets = NSEdgeInsets(top: 12, left: 14, bottom: 12, right: 14)
        hStack.translatesAutoresizingMaskIntoConstraints = false
        contentStack = hStack
        addSubview(hStack)

        let minimumHeight = heightAnchor.constraint(greaterThanOrEqualToConstant: 48)
        minimumHeight.priority = .defaultHigh

        NSLayoutConstraint.activate([
            hStack.topAnchor.constraint(equalTo: topAnchor),
            hStack.bottomAnchor.constraint(equalTo: bottomAnchor),
            hStack.leadingAnchor.constraint(equalTo: leadingAnchor),
            hStack.trailingAnchor.constraint(equalTo: trailingAnchor),
            minimumHeight,
        ])

        let iconView = NSImageView()
        if let img = NSImage(systemSymbolName: symbol, accessibilityDescription: nil) {
            let config = NSImage.SymbolConfiguration(pointSize: 13, weight: .medium)
            iconView.image = img.withSymbolConfiguration(config)
        }
        iconView.contentTintColor = theme.accentColor
        iconView.imageScaling = .scaleProportionallyDown
        iconView.translatesAutoresizingMaskIntoConstraints = false
        iconView.widthAnchor.constraint(equalToConstant: 16).isActive = true
        iconView.heightAnchor.constraint(equalToConstant: 16).isActive = true
        hStack.addArrangedSubview(iconView)

        let textLabel = NSTextField(labelWithString: label)
        textLabel.font = NSFont.systemFont(ofSize: 12.5, weight: .regular)
        textLabel.textColor = theme.textPrimary
        textLabel.lineBreakMode = .byWordWrapping
        textLabel.maximumNumberOfLines = 2
        textLabel.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
        textLabel.translatesAutoresizingMaskIntoConstraints = false
        hStack.addArrangedSubview(textLabel)

        setContentHuggingPriority(.required, for: .vertical)
        setContentCompressionResistancePriority(.required, for: .vertical)
    }

    required init?(coder: NSCoder) { fatalError() }

    override var intrinsicContentSize: NSSize {
        guard let contentStack else { return super.intrinsicContentSize }
        let fitting = contentStack.fittingSize
        return NSSize(width: NSView.noIntrinsicMetric, height: max(48, fitting.height))
    }

    override func updateTrackingAreas() {
        super.updateTrackingAreas()
        trackingAreas.forEach { removeTrackingArea($0) }
        addTrackingArea(NSTrackingArea(
            rect: bounds,
            options: [.mouseEnteredAndExited, .activeInKeyWindow, .inVisibleRect],
            owner: self,
            userInfo: nil
        ))
    }

    override func mouseEntered(with event: NSEvent) {
        NSAnimationContext.runAnimationGroup { ctx in
            ctx.duration = 0.12
            animator().layer?.backgroundColor = hoverBg
        }
    }

    override func mouseExited(with event: NSEvent) {
        NSAnimationContext.runAnimationGroup { ctx in
            ctx.duration = 0.12
            animator().layer?.backgroundColor = normalBg
        }
    }

    override func mouseDown(with event: NSEvent) {
        onTapped?()
    }

    override func resetCursorRects() {
        addCursorRect(bounds, cursor: .pointingHand)
    }
}

// MARK: - Welcome chips grid

class WelcomeChipsView: NSView {
    var onChipTapped: ((String) -> Void)?
    private let theme: PopoverTheme
    private weak var outerStackView: NSStackView?

    private let suggestions: [(String, String, String)]

    // Prompt chips are 1:1 with the Orbit guide library — every guide
    // gets a chip. The welcome panel shuffles this pool and shows 4
    // random chips on each popover open (see ensureWelcomeSuggestionSelection
    // in TerminalView+WelcomePanel.swift). Entries autogenerated from
    // get-orbit/lib/guides/*.tsx via Scripts/generate_chip_pool.py — to
    // refresh after a guide is added/edited/removed in get-orbit, re-run
    // the script and paste the output here.
    static let defaultSuggestionPool: [(String, String, String)] = [
        ("arrow.triangle.branch", "The first 72 hours decide who activates", "The first 72 hours decide who activates"),
        ("chart.bar.xaxis", "A/B testing in email: sample size, novelty, and what to r…", "A/B testing in email: sample size, novelty, and what to report"),
        ("arrow.triangle.branch", "Abandoned cart emails: what actually works", "Abandoned cart emails: what actually works"),
        ("chart.line.uptrend.xyaxis", "AI personalisation at scale: the architecture that actual…", "AI personalisation at scale: the architecture that actually works"),
        ("chart.bar.xaxis", "Measuring AI personalisation lift honestly", "Measuring AI personalisation lift honestly"),
        ("envelope.badge.shield.half.filled", "Apple Mail Privacy Protection, four years in", "Apple Mail Privacy Protection, four years in"),
        ("chart.bar.xaxis", "Attribution models for lifecycle: which one to defend in…", "Attribution models for lifecycle: which one to defend in which room"),
        ("chart.line.uptrend.xyaxis", "B2B lifecycle marketing: what changes when the buyer isn'…", "B2B lifecycle marketing: what changes when the buyer isn't the user"),
        ("envelope.badge.shield.half.filled", "BIMI: the logo-in-the-inbox feature, and whether it's wor…", "BIMI: the logo-in-the-inbox feature, and whether it's worth the effort"),
        ("arrow.triangle.branch", "Birthday and anniversary emails: the easy wins most progr…", "Birthday and anniversary emails: the easy wins most programs don't run"),
        ("envelope.badge.shield.half.filled", "Bounce rate management: the thresholds and the fix order", "Bounce rate management: the thresholds and the fix order"),
        ("envelope.badge.shield.half.filled", "Bounces vs blocks vs deferrals: what your ESP's error cod…", "Bounces vs blocks vs deferrals: what your ESP's error codes actually mean"),
        ("paintbrush.pointed", "Brand voice in lifecycle: how to sound like you, not the…", "Brand voice in lifecycle: how to sound like you, not the generic SaaS CRM voice"),
        ("paintbrush.pointed", "Liquid for lifecycle marketers — the complete Braze refer…", "Liquid for lifecycle marketers — the complete Braze reference"),
        ("paintbrush.pointed", "Braze naming conventions that survive a Friday afternoon", "Braze naming conventions that survive a Friday afternoon"),
        ("arrow.triangle.branch", "Browse abandonment: the program that sits between ads and…", "Browse abandonment: the program that sits between ads and cart"),
        ("chart.line.uptrend.xyaxis", "Building a lifecycle team — the roles, the order, the size", "Building a lifecycle team — the roles, the order, the size"),
        ("chart.line.uptrend.xyaxis", "The cadence question: how often should you email?", "The cadence question: how often should you email?"),
        ("chart.line.uptrend.xyaxis", "Choosing which lifecycle programs to build first", "Choosing which lifecycle programs to build first"),
        ("chart.bar.xaxis", "Churn cohort analysis: the one chart that tells you if re…", "Churn cohort analysis: the one chart that tells you if retention is actually improving"),
        ("chart.line.uptrend.xyaxis", "CRM vs CDP: which tool do you actually need?", "CRM vs CDP: which tool do you actually need?"),
        ("paintbrush.pointed", "Custom attributes: the data design that decides what your…", "Custom attributes: the data design that decides what your program can do"),
        ("envelope.badge.shield.half.filled", "Dedicated vs shared IP: the real decision", "Dedicated vs shared IP: the real decision"),
        ("envelope.badge.shield.half.filled", "The deliverability mental model: one picture for authenti…", "The deliverability mental model: one picture for authentication, reputation, content, and monitoring"),
        ("envelope.badge.shield.half.filled", "Domain vs IP reputation: which one actually matters", "Domain vs IP reputation: which one actually matters"),
        ("paintbrush.pointed", "Email accessibility: the seven rules that make your email…", "Email accessibility: the seven rules that make your emails readable by everyone"),
        ("paintbrush.pointed", "The email copywriting pyramid: write for the 5-second rea…", "The email copywriting pyramid: write for the 5-second reader first"),
        ("paintbrush.pointed", "Email dark mode: the four render modes and how to not bre…", "Email dark mode: the four render modes and how to not break any of them"),
        ("envelope.badge.shield.half.filled", "Email deliverability — the practitioner's guide", "Email deliverability — the practitioner's guide"),
        ("chart.bar.xaxis", "Send-time optimisation: what it really moves, and what it…", "Send-time optimisation: what it really moves, and what it doesn't"),
        ("paintbrush.pointed", "Emojis in subject lines: when they help, when they hurt", "Emojis in subject lines: when they help, when they hurt"),
        ("chart.line.uptrend.xyaxis", "Braze, Iterable, Customer.io, HubSpot — what each actuall…", "Braze, Iterable, Customer.io, HubSpot — what each actually gets right and wrong"),
        ("chart.bar.xaxis", "False positives in email A/B tests: why half of winning t…", "False positives in email A/B tests: why half of winning tests don't actually win"),
        ("arrow.triangle.branch", "Free shipping threshold emails: the cart-value nudge that…", "Free shipping threshold emails: the cart-value nudge that reliably lifts AOV"),
        ("paintbrush.pointed", "Generative AI for lifecycle content: where it earns its p…", "Generative AI for lifecycle content: where it earns its place and where it embarrasses you"),
        ("envelope.badge.shield.half.filled", "Why Gmail clips emails at 102KB (and how to stop it)", "Why Gmail clips emails at 102KB (and how to stop it)"),
        ("envelope.badge.shield.half.filled", "Gmail Promotions tab: is landing there actually bad?", "Gmail Promotions tab: is landing there actually bad?"),
        ("envelope.badge.shield.half.filled", "Google Postmaster Tools: a walkthrough for people who act…", "Google Postmaster Tools: a walkthrough for people who actually send email"),
        ("chart.bar.xaxis", "Holdout group design: the incrementality tool most lifecy…", "Holdout group design: the incrementality tool most lifecycle programs skip"),
        ("envelope.badge.shield.half.filled", "Inbox placement testing: seed lists, their limits, and wh…", "Inbox placement testing: seed lists, their limits, and what to do instead"),
        ("chart.bar.xaxis", "Incrementality testing: the measurement that tells you if…", "Incrementality testing: the measurement that tells you if a program actually works"),
        ("envelope.badge.shield.half.filled", "IP warm-up in Braze — the playbook that actually holds", "IP warm-up in Braze — the playbook that actually holds"),
        ("chart.line.uptrend.xyaxis", "The lifecycle audit — a 30-point checklist", "The lifecycle audit — a 30-point checklist"),
        ("chart.line.uptrend.xyaxis", "Lifecycle marketing for flat products", "Lifecycle marketing for flat products"),
        ("chart.line.uptrend.xyaxis", "Lifecycle for startups: the three flows to build before a…", "Lifecycle for startups: the three flows to build before anything else"),
        ("chart.line.uptrend.xyaxis", "The lifecycle metrics dashboard: what to track, what to i…", "The lifecycle metrics dashboard: what to track, what to ignore"),
        ("envelope.badge.shield.half.filled", "List hygiene: the six-rule policy", "List hygiene: the six-rule policy"),
        ("arrow.triangle.branch", "Loyalty program emails: the six touches that make a loyal…", "Loyalty program emails: the six touches that make a loyalty program work"),
        ("paintbrush.pointed", "Mobile email design: 65% of opens are on a phone — design…", "Mobile email design: 65% of opens are on a phone — design for that"),
        ("chart.line.uptrend.xyaxis", "The monthly newsletter still works — here's the structure", "The monthly newsletter still works — here's the structure"),
        ("arrow.triangle.branch", "Onboarding flows: signup to activated", "Onboarding flows: signup to activated"),
        ("paintbrush.pointed", "Personalisation that doesn't feel creepy", "Personalisation that doesn't feel creepy"),
        ("paintbrush.pointed", "Plain-text email versions: why they still matter in 2026", "Plain-text email versions: why they still matter in 2026"),
        ("arrow.triangle.branch", "Post-purchase emails: what to send after the receipt", "Post-purchase emails: what to send after the receipt"),
        ("chart.line.uptrend.xyaxis", "Predictive models in lifecycle: churn, propensity, and re…", "Predictive models in lifecycle: churn, propensity, and recommendations without the magic"),
        ("paintbrush.pointed", "Preheader text: the second subject line most programs ignore", "Preheader text: the second subject line most programs ignore"),
        ("arrow.triangle.branch", "Price increase emails: how to raise prices without a chur…", "Price increase emails: how to raise prices without a churn spike"),
        ("chart.bar.xaxis", "Price-testing through email: what's testable, what isn't", "Price-testing through email: what's testable, what isn't"),
        ("arrow.triangle.branch", "Product launch email sequence: the five emails that actua…", "Product launch email sequence: the five emails that actually sell a new product"),
        ("arrow.triangle.branch", "Progressive profiling: asking users for data without scar…", "Progressive profiling: asking users for data without scaring them off"),
        ("paintbrush.pointed", "Push notification copy that actually gets tapped", "Push notification copy that actually gets tapped"),
        ("chart.line.uptrend.xyaxis", "Quarterly planning for lifecycle: what actually goes in t…", "Quarterly planning for lifecycle: what actually goes in the plan"),
        ("arrow.triangle.branch", "Reactivation vs win-back: the distinction that changes th…", "Reactivation vs win-back: the distinction that changes the program"),
        ("arrow.triangle.branch", "Referral program emails — the three flows that make it work", "Referral program emails — the three flows that make it work"),
        ("arrow.triangle.branch", "Replenishment emails: the lifecycle flow that buys itself", "Replenishment emails: the lifecycle flow that buys itself"),
        ("chart.line.uptrend.xyaxis", "Reporting lifecycle to executives: the monthly update tha…", "Reporting lifecycle to executives: the monthly update that actually lands"),
        ("envelope.badge.shield.half.filled", "Reputation recovery: the 90-day playbook for dropping fro…", "Reputation recovery: the 90-day playbook for dropping from High to Low"),
        ("chart.line.uptrend.xyaxis", "Retention economics: proving lifecycle ROI to finance", "Retention economics: proving lifecycle ROI to finance"),
        ("arrow.triangle.branch", "Review request emails: the timing that actually produces…", "Review request emails: the timing that actually produces reviews"),
        ("chart.bar.xaxis", "Sample size: the calculation everyone gets wrong in email…", "Sample size: the calculation everyone gets wrong in email A/B tests"),
        ("chart.bar.xaxis", "Segment-based testing: when your average lift is hiding o…", "Segment-based testing: when your average lift is hiding opposing effects"),
        ("chart.line.uptrend.xyaxis", "Segmentation strategy: beyond RFM", "Segmentation strategy: beyond RFM"),
        ("paintbrush.pointed", "The SMS playbook from the operator's seat", "The SMS playbook from the operator's seat"),
        ("envelope.badge.shield.half.filled", "SMTP vs API sending: which integration pattern your progr…", "SMTP vs API sending: which integration pattern your program needs"),
        ("envelope.badge.shield.half.filled", "Spam complaints: the playbook for detecting and reducing…", "Spam complaints: the playbook for detecting and reducing them"),
        ("envelope.badge.shield.half.filled", "SPF, DKIM, and DMARC explained for lifecycle marketers", "SPF, DKIM, and DMARC explained for lifecycle marketers"),
        ("paintbrush.pointed", "Subject line anatomy: the four parts every line that perf…", "Subject line anatomy: the four parts every line that performs shares"),
        ("arrow.triangle.branch", "Subscription churn saves: the three-moment intervention t…", "Subscription churn saves: the three-moment intervention that retains 20%+ of cancellers"),
        ("arrow.triangle.branch", "Sunset sequences: how to say goodbye without burning the…", "Sunset sequences: how to say goodbye without burning the list"),
        ("arrow.triangle.branch", "Transactional emails: the highest-engagement messages you…", "Transactional emails: the highest-engagement messages you ignore"),
        ("paintbrush.pointed", "Transactional email anatomy: the five sections every tran…", "Transactional email anatomy: the five sections every transactional needs"),
        ("arrow.triangle.branch", "Trial-to-paid: the seven-email sequence that converts 20%…", "Trial-to-paid: the seven-email sequence that converts 20%+ of free users"),
        ("envelope.badge.shield.half.filled", "The unsubscribe page is the most important page in your l…", "The unsubscribe page is the most important page in your lifecycle program"),
        ("arrow.triangle.branch", "VIP customer lifecycle: how to treat the 5% of users who…", "VIP customer lifecycle: how to treat the 5% of users who drive 40% of revenue"),
        ("arrow.triangle.branch", "The welcome email sequence: the 7-day structure that works", "The welcome email sequence: the 7-day structure that works"),
        ("chart.line.uptrend.xyaxis", "What is lifecycle marketing? A field guide for operators…", "What is lifecycle marketing? A field guide for operators starting from zero"),
        ("arrow.triangle.branch", "Win-back flows: 12 patterns that earn their place", "Win-back flows: 12 patterns that earn their place"),
    ]

    // Kept for upstream compatibility — never surfaced now that Orion has no archive mode.
    static let starterPackSuggestionPool: [(String, String, String)] = defaultSuggestionPool

    init(theme: PopoverTheme, suggestions: [(String, String, String)] = WelcomeChipsView.defaultSuggestionPool) {
        self.theme = theme
        self.suggestions = suggestions
        super.init(frame: .zero)
        setupViews()
    }

    required init?(coder: NSCoder) { fatalError() }

    private func setupViews() {
        translatesAutoresizingMaskIntoConstraints = false

        let outerStack = NSStackView()
        outerStack.orientation = .vertical
        outerStack.alignment = .leading
        outerStack.spacing = 8
        outerStack.translatesAutoresizingMaskIntoConstraints = false
        outerStackView = outerStack
        addSubview(outerStack)

        NSLayoutConstraint.activate([
            outerStack.topAnchor.constraint(equalTo: topAnchor),
            outerStack.leadingAnchor.constraint(equalTo: leadingAnchor),
            outerStack.trailingAnchor.constraint(equalTo: trailingAnchor),
            outerStack.bottomAnchor.constraint(equalTo: bottomAnchor),
        ])

        let pairs = stride(from: 0, to: suggestions.count, by: 2).map { i -> [(String, String, String)] in
            let end = min(i + 2, suggestions.count)
            return Array(suggestions[i..<end])
        }

        for pair in pairs {
            let rowStack = NSStackView()
            rowStack.orientation = .horizontal
            rowStack.alignment = .centerY
            rowStack.spacing = 8
            rowStack.distribution = .fillEqually
            rowStack.translatesAutoresizingMaskIntoConstraints = false

            for (symbol, label, sendText) in pair {
                let chip = HoverChipView(symbol: symbol, label: label, theme: theme)
                chip.onTapped = { [weak self] in self?.onChipTapped?(sendText) }
                rowStack.addArrangedSubview(chip)
            }
            outerStack.addArrangedSubview(rowStack)
            rowStack.widthAnchor.constraint(equalTo: outerStack.widthAnchor).isActive = true
        }

        setContentHuggingPriority(.required, for: .vertical)
        setContentCompressionResistancePriority(.required, for: .vertical)
    }

    override var intrinsicContentSize: NSSize {
        guard let outerStackView else { return super.intrinsicContentSize }
        let fitting = outerStackView.fittingSize
        return NSSize(width: NSView.noIntrinsicMetric, height: fitting.height)
    }
}

/// 2-chip horizontal row showing LLM-generated follow-up suggestions
/// after a substantive assistant response. Real estate inside the
/// popover is tight, so 2 chips per row — same hover affordance as
/// the welcome chips but rendered without the symbol icon (the
/// follow-ups are purely text-driven).
class FollowUpChipsView: NSView {
    var onChipTapped: ((String) -> Void)?
    private let theme: PopoverTheme
    private let chips: [String]
    private weak var rowStack: NSStackView?

    init(theme: PopoverTheme, chips: [String]) {
        self.theme = theme
        self.chips = chips
        super.init(frame: .zero)
        setupViews()
    }

    required init?(coder: NSCoder) { fatalError() }

    private func setupViews() {
        translatesAutoresizingMaskIntoConstraints = false

        let stack = NSStackView()
        stack.orientation = .horizontal
        stack.alignment = .centerY
        stack.spacing = 8
        stack.distribution = .fillEqually
        stack.translatesAutoresizingMaskIntoConstraints = false
        addSubview(stack)
        rowStack = stack

        NSLayoutConstraint.activate([
            stack.topAnchor.constraint(equalTo: topAnchor),
            stack.leadingAnchor.constraint(equalTo: leadingAnchor),
            stack.trailingAnchor.constraint(equalTo: trailingAnchor),
            stack.bottomAnchor.constraint(equalTo: bottomAnchor),
        ])

        for chipText in chips.prefix(2) {
            // Reuse the same hover/symbol chip widget the welcome panel
            // uses, with `arrow.right` indicating "send this as the next
            // question". Symbol stays consistent across both chips so
            // they read as a paired action, not categorised content.
            let chip = HoverChipView(symbol: "arrow.right", label: chipText, theme: theme)
            chip.onTapped = { [weak self] in self?.onChipTapped?(chipText) }
            stack.addArrangedSubview(chip)
        }

        setContentHuggingPriority(.required, for: .vertical)
        setContentCompressionResistancePriority(.required, for: .vertical)
    }
}

class ConnectionSetupCardView: NSView {
    var onOpenSettings: (() -> Void)?

    private let theme: PopoverTheme

    init(theme: PopoverTheme) {
        self.theme = theme
        super.init(frame: .zero)
        setupViews()
    }

    required init?(coder: NSCoder) { fatalError() }

    private func setupViews() {
        translatesAutoresizingMaskIntoConstraints = false
        wantsLayer = true
        layer?.backgroundColor = theme.inputBg.cgColor
        layer?.cornerRadius = 12
        layer?.borderWidth = 1
        layer?.borderColor = theme.separatorColor.withAlphaComponent(0.45).cgColor

        let stack = NSStackView()
        stack.orientation = .vertical
        stack.alignment = .leading
        stack.spacing = 8
        stack.translatesAutoresizingMaskIntoConstraints = false
        addSubview(stack)

        NSLayoutConstraint.activate([
            stack.topAnchor.constraint(equalTo: topAnchor, constant: 12),
            stack.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 14),
            stack.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -14),
            stack.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -12)
        ])

        let title = NSTextField(wrappingLabelWithString: "Set up your AI connection")
        title.font = NSFont.systemFont(ofSize: 13, weight: .semibold)
        title.textColor = theme.textPrimary
        title.maximumNumberOfLines = 0
        stack.addArrangedSubview(title)
        title.widthAnchor.constraint(equalTo: stack.widthAnchor).isActive = true

        let body = NSTextField(wrappingLabelWithString: "Open Settings to connect Claude, Codex/ChatGPT, or OpenAI. Once one is connected, Orion is ready to chat.")
        body.font = NSFont.systemFont(ofSize: 12, weight: .regular)
        body.textColor = theme.textDim
        body.maximumNumberOfLines = 0
        stack.addArrangedSubview(body)
        body.widthAnchor.constraint(equalTo: stack.widthAnchor).isActive = true

        let settingsButton = HoverButton(title: "", target: self, action: #selector(openSettingsTapped))
        settingsButton.isBordered = false
        settingsButton.wantsLayer = true
        settingsButton.normalBg = theme.accentColor.cgColor
        settingsButton.hoverBg = theme.accentColor.withAlphaComponent(0.82).cgColor
        settingsButton.layer?.backgroundColor = settingsButton.normalBg
        settingsButton.layer?.cornerRadius = 12
        settingsButton.horizontalContentPadding = 16
        settingsButton.verticalContentPadding = 6
        settingsButton.attributedTitle = NSAttributedString(string: "Open Settings", attributes: [
            .font: NSFont.systemFont(ofSize: 12, weight: .semibold),
            .foregroundColor: NSColor.white
        ])
        settingsButton.translatesAutoresizingMaskIntoConstraints = false
        settingsButton.heightAnchor.constraint(equalToConstant: 34).isActive = true
        stack.addArrangedSubview(settingsButton)

        setContentHuggingPriority(.required, for: .vertical)
        setContentCompressionResistancePriority(.required, for: .vertical)
    }

    @objc private func openSettingsTapped() {
        onOpenSettings?()
    }
}
